apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:       # How to update pods
    type: RollingUpdate      # Zero downtime update strategy
    rollingUpdate:
      maxUnavailable: 1   # Update garda max 1 pod offline huna sakcha
      maxSurge: 1          # Update garda max 1 pod offline huna sakcha
  selector:
    matchLabels:  # app=nginx label vako pods matrai manage garne
      app: nginx
  template:          # Pod template how to create pods
    metadata:
      labels:
        app: nginx        # Must match selector!
        version: v1
    spec:       # Pod specification
      containers:
      - name: nginx
        image: nginx:1.25   # Docker image - specific version
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
